Compile with clang
Change the variable name for the NodeList::ConstIterator to 'it' instead
of 'i', since it shadows the int 'i' declaration in the for() loop:

htmlgenerator.cpp:1350:33: error: redefinition of 'i' with a different
type
        NodeList::ConstIterator i = nl.begin();
                                ^
htmlgenerator.cpp:1332:14: note: previous definition is here
    for (int i=0; i<collisionNodes.size(); ++i) {
             ^

Change-Id: I5a422816b3f20cd738e14ffa52bb12423eac0295
Sanity-Review: Qt Sanity Bot <qt_sanity_bot@ovi.com>
Reviewed-by: Martin Smith <martin.smith@nokia.com>